/*
 * Generated by erpcgen 1.13.0 on Tue Jul 23 19:34:30 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_example_client_h_)
#define _c_example_client_h_

#include "example_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief IO identifiers */
enum _IO_ids
{
    kIO_service_id = 1,
    kIO_say_hi_id = 1,
};

//! @name IO
//@{
char * say_hi(const char * name);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initIO_client(erpc_client_t client);

void deinitIO_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_example_client_h_
