/*
 * Generated by erpcgen 1.13.0 on Tue Jul 23 19:34:30 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "c_example_client.h"
#include "example_client.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
IO_client *s_IO_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(IO_client, s_IO_client);
#endif

char * say_hi(const char * name)
{
    char * result = NULL;
    result = s_IO_client->say_hi(name);

    return result;
}

void initIO_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_IO_client == nullptr);
    s_IO_client = new IO_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_IO_client.isUsed());
    s_IO_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitIO_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_IO_client != nullptr)
    {
        delete s_IO_client;
        s_IO_client = nullptr;
    }
#else
    s_IO_client.destroy();
#endif
}
