/*
 * Generated by erpcgen 1.13.0 on Tue Jul 23 19:34:30 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_example_server_h_)
#define _c_example_server_h_

#include "example_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief IO identifiers */
enum _IO_ids
{
    kIO_service_id = 1,
    kIO_say_hi_id = 1,
};

//! @name IO
//@{
char * say_hi(const char * name);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return IO_service service object. */
erpc_service_t create_IO_service(void);

/*! @brief Destroy IO_service service object. */
void destroy_IO_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_example_server_h_
