/*
 * Generated by erpcgen 1.13.0 on Tue Jul 23 17:26:28 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_example_interface_hpp_)
#define _example_interface_hpp_

#include "example_common.hpp"

namespace erpcShim
{


// Abstract base class for IO
class IO_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_set_ledId = 1;

        virtual ~IO_interface(void);

        virtual void set_led(LEDName whichLed, bool onOrOff) = 0;
private:
};
} // erpcShim


#endif // _example_interface_hpp_
