/*
 * Generated by erpcgen 1.13.0 on Tue Jul 23 19:34:30 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_example_interface_hpp_)
#define _example_interface_hpp_

#include "example_common.hpp"

namespace erpcShim
{


// Abstract base class for IO
class IO_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_say_hiId = 1;

        virtual ~IO_interface(void);

        virtual char * say_hi(const char * name) = 0;
private:
};
} // erpcShim


#endif // _example_interface_hpp_
