/*
 * Generated by erpcgen 1.13.0 on Tue Jul 23 19:34:30 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_example_server_hpp_)
#define _example_server_hpp_

#include "example_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for IO.
 */
class IO_service : public erpc::Service
{
public:
    IO_service(IO_interface *_IO_interface);

    virtual ~IO_service();

    /*! @brief return service interface handler. */
    IO_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    IO_interface *m_handler;
    /*! @brief Server shim for say_hi of IO interface. */
    erpc_status_t say_hi_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _example_server_hpp_
