/*
 * Generated by erpcgen 1.13.0 on Tue Jul 23 17:26:28 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_example_client_hpp_)
#define _example_client_hpp_

#include "example_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class IO_client: public IO_interface
{
    public:
        IO_client(erpc::ClientManager *manager);

        virtual ~IO_client();

        virtual void set_led(LEDName whichLed, bool onOrOff);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _example_client_hpp_
