/*
 * Generated by erpcgen 1.13.0 on Tue Jul 23 19:34:30 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "example_interface.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

IO_interface::~IO_interface(void)
{
}
