/*
 * Generated by erpcgen 1.13.0 on Tue Jul 23 17:26:28 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_example_common_h_)
#define _example_common_h_

#if defined(__cplusplus)
extern "C"
{
#endif
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "erpc_version.h"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_ERPCSHIM)
#define ERPC_TYPE_DEFINITIONS_ERPCSHIM

// Enumerators data types declarations
typedef enum LEDName
{
    kRed = 0,
    kGreen = 1,
    kBlue = 2
} LEDName;

#endif // ERPC_TYPE_DEFINITIONS_ERPCSHIM

#if defined(__cplusplus)
}
#endif

#endif // _example_common_h_
